import Navbar from '@/components/navbar/Navbar'
import { Inter } from 'next/font/google'
import './globals.css'
import FooterPage from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
        <body className={inter.className}>
          <div className='mainContainer'>
            <Navbar/>
              {children}
            <FooterPage/>
          </div>
        </body>
      </>
    </html>
  )
}
